### ISSUE TITLE
My profile appears empty

### ISSUE THREAD

**Issue by klaaspieter** [sourcerer-io/sourcerer-app#300] opened 2018-07-02 12:50 UTC
After two scans my profile is still empty. I believe this is a duplicate of #293 but decided to file a separate issue so the original author isn't notified of changes.

**Comment by anatolystansler** [comment] 2018-07-02 14:19
Hi @klaaspieter !

Thank you for creating an issue! You are right, it's a duplicate of #293. Fixed your profile manually for now. We working on a fix.

Closing this issue, feel free to reopen it if you still have any problems.

**Closed by anatolystansler** 2018-07-02 14:19 UTC
