### ISSUE TITLE
Can't activate account

### ISSUE THREAD

**Issue by kounelios13** [sourcerer-io/sourcerer-app#205] opened 2018-02-11 18:41 UTC
en I clickHello 
I created an account today and I opened my email to activate my account.
However when I click the "Confirm email address" the page that opens up says that "This page could not be found".

As a result I can't activate my account.
What is going on?

**Comment by sergey-surkov** [comment] 2018-02-11 18:43
Hi,

We are looking into it. Sorry for the inconvenience.

Best,
Sergey

**Comment by drAlberT** [comment] 2018-02-11 21:44
Same for me.

 I was logged in even if the link on the confirmation email gave this error .. but, once i logged out, I wasn't able to find a "login" link ...

**Comment by osilla** [comment] 2018-02-12 00:55
hi all - a fix was just pushed to production.

let us know if you still encounter this issue.

**Comment by drAlberT** [comment] 2018-02-12 09:59
I still can't find a "login" .. the only way I found to be logged in is to re-do the "build with GH" procedure .. is it the intended behavior?

**Comment by drAlberT** [comment] 2018-02-12 10:13
I'm talking about the web page, seen by mobile .. looks like an UX issue then ..  from desktop it is ok

**Comment by osilla** [comment] 2018-02-12 15:59
@drAlberT it was a UX issue.  we just pushed the fix to production.  you should now be able to reach our Sign in page appropriately.

**Comment by anatolykislov** [comment] 2018-02-12 16:00
@drAlberT "login" or "sign in" button located in "burger" menu in mobile version, unfortunately it redirected to "sign up" page. Email confirmation and "Sign in" link is fixed now.
Thank you for contacting us.

**Closed by osilla** 2018-02-12 15:59 UTC

**Comment by drAlberT** [comment] 2018-02-12 17:23
perfect..  it works, thanks
